// Bindings access. With Astro 7 + @astrojs/cloudflare unified entrypoint,
// locals.runtime.env was removed — bindings come from cloudflare:workers.
// Runtime types (D1Database, R2Bucket, cloudflare:workers) come from
// worker-configuration.d.ts, generated by `wrangler types`.
import { env } from "cloudflare:workers";

export const runtimeEnv = env as unknown as {
  DB: D1Database;
  MEDIA: R2Bucket;
  GITHUB_TOKEN?: string;
  GITHUB_REPO?: string;
  ACCESS_TEAM?: string;
  ACCESS_AUD?: string;
  TURNSTILE_SECRET?: string;
};
