// Bindings access. With Astro 7 + @astrojs/cloudflare unified entrypoint,
// locals.runtime.env was removed — bindings come from cloudflare:workers.
// Runtime types (D1Database, R2Bucket, cloudflare:workers) come from
// worker-configuration.d.ts, generated by `wrangler types`.
import { env } from "cloudflare:workers";

export const runtimeEnv = env as unknown as {
  DB: D1Database;
  MEDIA: R2Bucket;
  AUTH_PASSWORD?: string;
  GITHUB_TOKEN?: string;
  GITHUB_REPO?: string;
  TURNSTILE_SECRET?: string;
  // OAuth (each provider activates when both its secrets exist)
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  AUTHOR_EMAILS?: string; // comma-separated allow-list of accounts
};
